#!/bin/bash

export NYCDB_DATABASE_VOLUME_NAME="nycdb_test-database-data"

if docker volume inspect "$NYCDB_DATABASE_VOLUME_NAME" > /dev/null; then
   docker volume rm "$NYCDB_DATABASE_VOLUME_NAME" > /dev/null
fi

# docker-compose build
docker-compose run --rm --entrypoint="pytest tests" nycdb
