create table if not exists complaints_311 (
  Unique_Key bigint UNIQUE NOT NULL,
  Created_Date date,
  Closed_Date date,
  Agency text,
  Agency_Name text,
  Complaint_Type text,
  Descriptor text,
  Location_Type text,
  Incident_Zip char(5),
  Incident_Address text,
  Street_Name text,
  Cross_Street_1 text,
  Cross_Street_2 text,
  Intersection_Street_1 text,
  Intersection_Street_2 text,
  Address_Type text,
  City text,
  Landmark text,
  Facility_Type text,
  Status text,
  Due_Date date,
  Resolution_Description text,
  Resolution_Action_Updated_Date date,
  Community_Board text,
  Borough text,
  X_Coordinate integer,
  Y_Coordinate integer,
  Park_Facility_Name text,
  Park_Borough text,
  School_Name text, 
  School_Number text,
  School_Region text,
  School_Code text,
  School_Phone_Number text,
  School_Address text,
  School_City text,
  School_State text,
  School_Zip text,
  School_Not_Found boolean,
  School_or_Citywide_Complaint text,
  Vehicle_Type text,
  Taxi_Company_Borough text,
  Taxi_Pick_Up_Location text,
  Bridge_Highway_Name text,
  Bridge_Highway_Direction text,
  Road_Ramp text,
  Bridge_Highway_Segment text,
  Garage_Lot_Name text,
  Ferry_Direction text,
  Ferry_Terminal_Name text,
  Latitude float,
  Longitude float,
  Location text,
  bbl char(10)
);


